version: '3.9'
services:
  log-analyzer-front:
    build:
      context : .
      args:
        - VARIANT=${VARIANT}
      dockerfile: Dockerfile
    image: log-analyzer-front
    container_name: devcontainer-log-analyzer-front
    command: sleep infinity
    volumes:
      - ../:/code/dev
      - ~/.gitconfig/:/home/dev/.gitconfig
    user: dev